packages:
  - .
  - vscode-extension

overrides:
  '@automerge/automerge': 3.3.0-fragments.2
  '@automerge/automerge-repo': 2.6.0-subduction.44
  '@automerge/automerge-repo-network-websocket': 2.6.0-subduction.44

allowBuilds:
  '@vscode/vsce-sign': true
  cbor-extract: true
  esbuild: true
  keytar: true
  lmdb: true
  msgpackr-extract: true

onlyBuiltDependencies:
  - esbuild

minimumReleaseAgeExclude:
  - '@automerge/automerge-repo-network-websocket@2.6.0-subduction.44'
  - '@automerge/automerge-repo@2.6.0-subduction.44'
